version: '3'

services:
  php:
    env_file:
      - .env.local
    image: mushuledragon/acseo
    ports:
      - ${PHP_PORT:-80}:80
  db:
    env_file:
      - .env.local
    image: mushuledragon/acseo_db
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD:-toor}
      - MYSQL_DATABASE=${PROJECT_NAME}_db
  pma:
    env_file:
      - .env.local
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PMA_PORT:-81}:80
    links:
      - db
    environment:
      - PMA_HOST=db
      - PMA_USER=${DATABASE_USER:-root}
      - PMA_PASSWORD=${DATABASE_PASSWORD:-toor}
      - PMA_PORT=${DATABASE_PORT:-3306}
